

# Permalinks
permalink:        pretty

# Setup
title:            Athena's Moments
tagline:          'Athena Rhodes'
description:      'Athena Rhodes'
url:              http://foopod.github.io/matapihi
baseurl:          /

author:
  name:           'Athena Rhodes'
  url:            https://twitter.com/athena

paginate:         6

gems:
  - jekyll-paginate
  - jekyll-gist
  
# Custom
instagram : wild_for_wildlifes